apiVersion: apps/v1
kind: Deployment
metadata:
  name: coreapp2-deployment
spec:
  selector:
    matchLabels:
      app: coreapp2
  template:
    metadata:
      labels:
        app: coreapp2
    spec:
      containers:
      - name: coreapp2
        image: claimproc001.azurecr.io/coreapp2:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: coreapp2-service
spec:
  selector:
    app: coreapp2
  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer
